[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { workspace = true }
infrastructure = { workspace = true }

axum = { workspace = true }
anyhow = { workspace = true }
tracing={workspace = true}
common = {workspace = true}
tokio = {workspace = true}
